import { useQuery } from '@tanstack/react-query';
import { useEffect, useRef } from 'react';
import { useParams } from 'react-router-dom';
import { fmtPhone } from '../../../lib/format';
import { generateContactSheet, logExport } from '../../../lib/rpc';
import { supabase } from '../../../lib/supabase';
import { WARNING_META } from '../../../lib/warnings';
import type { ContactSheetRow, WarningCode } from '../../../types/domain';

function selectedDots(batchId: string): number[] | null {
  try {
    const raw = window.sessionStorage.getItem(`sheet:${batchId}`);
    if (!raw) return null;
    const value: unknown = JSON.parse(raw);
    if (!Array.isArray(value)) return null;
    const dots = value.map(Number).filter((dot) => Number.isSafeInteger(dot) && dot > 0);
    return dots.length ? dots : null;
  } catch {
    return null;
  }
}

async function loadSheet(batchId: string): Promise<{
  batch: { name: string; customer: string | null; job: string | null };
  rows: ContactSheetRow[];
  generatedBy: string;
}> {
  const dots = selectedDots(batchId);
  const [rows, batchResult, sessionResult] = await Promise.all([
    generateContactSheet(batchId, dots),
    supabase.from('batches').select('name, customer, job').eq('id', batchId).single(),
    supabase.auth.getSession(),
  ]);
  if (batchResult.error) throw batchResult.error;
  const userId = sessionResult.data.session?.user.id;
  let generatedBy = sessionResult.data.session?.user.email ?? 'Twisted Nail';
  if (userId) {
    const profileResult = await supabase.from('profiles').select('full_name, email').eq('id', userId).maybeSingle();
    if (profileResult.data) generatedBy = profileResult.data.full_name || profileResult.data.email;
  }
  return { batch: batchResult.data, rows, generatedBy };
}

function warningLabels(reasons: string[]): string {
  return reasons
    .map((reason) => WARNING_META[reason as WarningCode]?.label ?? reason)
    .join('; ');
}

export default function ContactSheet() {
  const { batchId } = useParams<{ batchId: string }>();
  const logged = useRef(false);
  const query = useQuery({
    queryKey: ['contact-sheet', batchId],
    queryFn: () => loadSheet(batchId as string),
    enabled: Boolean(batchId),
    staleTime: 0,
  });

  useEffect(() => {
    if (!batchId || !query.data || logged.current) return;
    logged.current = true;
    void logExport(batchId, 'call_sheet', query.data.rows.length).catch(() => {
      logged.current = false;
    });
    const timer = window.setTimeout(() => window.print(), 250);
    return () => window.clearTimeout(timer);
  }, [batchId, query.data]);

  if (!batchId) return <div className="p-8">Missing batch ID.</div>;
  if (query.isPending) return <div className="min-h-dvh bg-white p-10 text-black">Preparing contact sheet…</div>;
  if (query.isError) return <div className="min-h-dvh bg-white p-10 text-black">Contact sheet unavailable. {query.error instanceof Error ? query.error.message : ''}</div>;

  const { batch, rows, generatedBy } = query.data;
  return (
    <div className="min-h-dvh bg-white p-8 text-black print:p-0">
      <style>{`@media print { @page { size: landscape; margin: 0.45in; } .print-hidden { display:none!important; } body { background:#fff!important; } }`}</style>
      <header className="border-b-2 border-black pb-4">
        <div className="flex items-start justify-between gap-8">
          <div><h1 className="text-2xl font-extrabold">{batch.name}</h1><div className="mt-1 text-sm">{batch.customer || 'No customer'}{batch.job ? ` · ${batch.job}` : ''}</div></div>
          <div className="text-right text-xs"><div>{new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div><div>Generated by {generatedBy}</div><div>{rows.length} contactable carrier{rows.length === 1 ? '' : 's'}</div></div>
        </div>
      </header>

      <div className="print-hidden my-4 flex justify-end"><button type="button" onClick={() => window.print()} className="bg-accent px-4 py-2 text-xs font-bold text-accent-ink">Print</button></div>

      {rows.length === 0 ? <div className="py-16 text-center">No contactable carriers are available for this selection. Do-not-contact carriers are excluded automatically.</div> : (
        <table className="mt-4 w-full border-collapse text-[10px]">
          <thead><tr className="border-y border-black text-left uppercase"><th className="py-2 pr-2">#</th><th className="py-2 pr-2">Carrier</th><th className="py-2 pr-2">Contact</th><th className="py-2 pr-2">Phone / Cell</th><th className="py-2 pr-2">Email</th><th className="py-2 pr-2">City</th><th className="py-2 pr-2">Status</th><th className="py-2">Warnings / notes</th></tr></thead>
          <tbody>{rows.map((row, index) => <tr key={row.dot_number} className="border-b border-black/25 align-top"><td className="py-2 pr-2 font-mono">{index + 1}</td><td className="py-2 pr-2"><strong>{row.legal_name}</strong>{row.dba_name ? <><br />DBA {row.dba_name}</> : null}<br /><span className="font-mono">USDOT {row.dot_number}</span></td><td className="py-2 pr-2">{row.contact_name || '—'}</td><td className="py-2 pr-2 font-mono">{fmtPhone(row.phone)}{row.cell_phone ? <><br />{fmtPhone(row.cell_phone)}</> : null}</td><td className="py-2 pr-2">{row.email || '—'}</td><td className="py-2 pr-2">{row.phy_city || '—'}, {row.phy_state || 'TX'}</td><td className="py-2 pr-2">{row.status.replaceAll('_', ' ')}</td><td className="py-2"><span className="text-[9px]">{warningLabels(row.warning_reasons)}</span><div className="mt-3 border-b border-black/40" /></td></tr>)}</tbody>
        </table>
      )}
    </div>
  );
}
